### ISSUE TITLE
Lubuntu 16.04 x64 after installing gtk+-3.0: ** (giphytool:3277): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

### ISSUE THREAD

**Issue by malonnnn** [csucu/giphytool#1]
Is this only meant for Ubuntu?

`** (giphytool:3277): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
`

**Comment by csucu** [comment]
Nope, but I've only tested this on Xubuntu 16.04. I'll have a look into it.

**Comment by csucu** [comment]
I was able to reproduce this on lubuntu. Installing the package at-spi2-core seemed to fix it.
