### ISSUE TITLE
doesn't seem to work and leaves process running

### ISSUE THREAD

**Issue by agiokas-dbg** [csucu/giphytool#2]
hi,

I've built it on Ubuntu 18.04, and the binary is there.
when I run it without parameters, I get:

```bash
$ giphytool

(giphytool:8103): GdkPixbuf-CRITICAL **: 10:24:03.682: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(giphytool:8103): GdkPixbuf-CRITICAL **: 10:24:03.682: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
```

Then, I can see a zombie process:
```
$ ps -ef | grep giphytool
alexgio+  8106  2539  0 10:24 ?        00:00:00 giphytool
alexgio+  8502  7666  0 10:25 pts/11   00:00:00 grep --color=auto giphytool
```

When I run it with a parameter:

```
giphytool -c cyberpunk-pixel-art-gif-5.gif 
```

I end up with a black window which does not show the GIF but rather the sign of image failure (see attached).
Is this something you could help with?

![Screenshot from 2019-11-15 10-26-48](https://user-images.githubusercontent.com/54706293/68936507-a13d7300-0792-11ea-9e7f-44b67faf5078.png)

**Comment by csucu** [comment]
Should be fixed now
